In [1]:
import stagcorr.correlators.main as corr
import stagcorr.stagFuncs as stagFuncs
import stagcorr.correlators.npointFree as npointFree
import stagcorr.correlators.twoPointsFreeFixed as twoPointsFreeFixed
import stagcorr.correlators.twoPointsFree as twoPointsFree
import stagcorr.correlators.threePointsFreeFixed as threePointsFreeFixed
import stagcorr.correlators.threePointsFree as threePointsFree
import importlib as imp
import numpy as np

imp.reload(corr)
imp.reload(npointFree)
imp.reload(twoPointsFreeFixed)
imp.reload(twoPointsFree)
imp.reload(threePointsFreeFixed)
imp.reload(threePointsFree)
imp.reload(stagFuncs)

<module 'stagcorr.stagFuncs' from '/mnt/c/Users/Shaun/pCloud/Physics/projects/stagcorr/stagcorr/stagFuncs.py'>

In [2]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GXT", 1, 0, [0,-1,-1],True],
                       spinTasteMassNaikMomDag2=["G5", "GXT", 1, 0, [0,1,1],True],
                       spinTasteMassNaikMomDag3=["G5", "G5Z", 1, 0, [0,0,1],False],
                       spinTasteMassNaikMomDag4=["G5", "G5Z", 1, 0, [0,0,-1],False],
                       volume=(6,6,6,6))

print(np.divide([ct[2,1,1,0], ct[3,2,1,0], ct[4,3,1,0], ct[5,4,1,0], ct[0,5,1,0]], 6**3))

ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GXT", 1, 0, [0,-1,-1],True],
                       spinTasteMassNaikMomDag2=["G5", "GXT", 1, 0, [0,1,1],True],
                       spinTasteMassNaikMomDag3=["G5", "G5Z", 1, 0, [0,0,-1],False],
                       spinTasteMassNaikMomDag4=["G5", "G5Z", 1, 0, [0,0,1],False],
                       volume=(6,6,6,6))

print(np.divide([ct[2,1,1,0], ct[3,2,1,0], ct[4,3,1,0], ct[5,4,1,0], ct[0,5,1,0]], 6**3))

new implementation


/home/shaun/my-venv/lib/python3.12/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


test1
test5
test2
test5
test2
test4
test1
test4
[ 9.03073580e-06-8.14200768e-23j -1.93262902e-06-4.35131303e-23j
 -1.12846983e-06+2.87478155e-23j -1.93262902e-06-3.81036448e-23j
  9.03073580e-06-9.64084614e-23j]
new implementation
test1
test5
test2
test5
test2
test4
test1
test4
[ 1.02931854e-06-7.03743931e-23j -7.38861642e-07+3.62923996e-23j
 -2.90338019e-07+1.44888402e-23j -7.38861642e-07+2.28881976e-23j
  1.02931854e-06-1.04354201e-22j]


## old implementation

In [8]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GXT", 1, 0, [0,1,1],False],
                       spinTasteMassNaikMomDag2=["G5", "GXT", 1, 0, [0,-1,-1],False],
                       spinTasteMassNaikMomDag3=["G5", "G5Z", 1, 0, [0,0,1],False],
                       spinTasteMassNaikMomDag4=["G5", "G5Z", 1, 0, [0,0,-1],False],
                       volume=(6,6,6,6))

print(np.divide([ct[2,1,1,0], ct[3,2,1,0], ct[4,3,1,0], ct[5,4,1,0], ct[0,5,1,0]], 6**3))

ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GXT", 1, 0, [0,1,1],False],
                       spinTasteMassNaikMomDag2=["G5", "GXT", 1, 0, [0,-1,-1],False],
                       spinTasteMassNaikMomDag3=["G5", "G5Z", 1, 0, [0,0,-1],False],
                       spinTasteMassNaikMomDag4=["G5", "G5Z", 1, 0, [0,0,1],False],
                       volume=(6,6,6,6))

print(np.divide([ct[2,1,1,0], ct[3,2,1,0], ct[4,3,1,0], ct[5,4,1,0], ct[0,5,1,0]], 6**3))

old (incorrect) implementation
[ 9.03073580e-06+2.07778467e-22j -1.93262902e-06-4.44416055e-23j
 -1.12846983e-06-1.87808838e-23j -1.93262902e-06-2.29168195e-23j
  9.03073580e-06+2.02624570e-22j]
old (incorrect) implementation
[ 1.02931854e-06+4.68176809e-23j -7.38861642e-07-1.83014553e-24j
 -2.90338019e-07-2.29077948e-23j -7.38861642e-07-2.01555812e-23j
  1.02931854e-06-2.42898189e-22j]


## 2pts

In [2]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GXT", 1, 0, [1,2,3],False],
                       spinTasteMassNaikMomDag2=["G5", "GXT", 1, 0, [-1,-2,-3],False],
                       volume=(6,6,6,6))

ct[:,0] / 6**3

/home/shaun/my-venv/lib/python3.12/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


test2
test4
test2
test4


array([-0.01683067-2.67748137e-19j, -0.00321953-2.29156212e-20j,
       -0.00023456+3.46293458e-21j, -0.00011525-1.03683926e-21j,
       -0.00023456+3.21774898e-21j, -0.00321953-1.60899780e-20j])

In [3]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GXT", 1, 0, [1,2,3],True],
                       spinTasteMassNaikMomDag2=["G5", "GXT", 1, 0, [1,2,3],False],
                       volume=(6,6,6,6))

ct[:,0] / 6**3

test2
test5
test1
test4


array([0.02162847-1.78216998e-19j, 0.00562414-2.30986621e-21j,
       0.00030035+3.18195546e-21j, 0.00017491-5.88254999e-22j,
       0.00030035+1.12894578e-20j, 0.00562414+1.04974843e-21j])

In [4]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "G5", 0.1, 0, [0,0,0],True],
                       spinTasteMassNaikMomDag2=["G5", "G5", 0.1, 0, [0,0,0],False],
                       volume=(4,4,4,4))

ct[:,0] / 4**3

test3
test4
test3
test4


array([1.90503915e-01+0.j, 1.07500068e-01+0.j, 2.04951852e-33+0.j,
       1.07500068e-01+0.j])

In [4]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "G5", 0.1, 0, [0,0,1],True],
                       spinTasteMassNaikMomDag2=["G5", "G5", 0.1, 0, [0,0,1],False],
                       volume=(4,4,4,4))

ct[:,0] / 4**3

array([ 1.13706687e-01-6.56465776e-20j,  6.75530884e-02-1.58889220e-33j,
       -1.62252714e-33+2.27513809e-33j,  6.75530884e-02+2.74445017e-33j])

In [8]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "G5X", 0.1, 0, [0,0,1],True],
                       spinTasteMassNaikMomDag2=["G5", "G5X", 0.1, 0, [0,0,1],False],
                       volume=(4,4,4,4))

print(np.real(ct[:,0] / 4**3))

ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "G5X", 0.1, 0, [1,0,0],True],
                       spinTasteMassNaikMomDag2=["G5", "G5X", 0.1, 0, [1,0,0],False],
                       volume=(4,4,4,4))

print(np.real(ct[:,0] / 4**3))

[4.11657705e-02 5.55458663e-02 2.20080872e-33 5.55458663e-02]
[5.68533433e-02 3.37765442e-02 3.08079281e-33 3.37765442e-02]


array([5.68533433e-02, 3.37765442e-02, 3.08079281e-33, 3.37765442e-02])

In [7]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "G5X", 0.1, 0, [0,0,1],True],
                       spinTasteMassNaikMomDag2=["G5", "G5X", 0.1, 0, [0,0,1],False],
                       volume=(6,6,6,6))

print(np.real(ct[:,0] / 6**3))

ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "G5X", 0.1, 0, [1,0,0],True],
                       spinTasteMassNaikMomDag2=["G5", "G5X", 0.1, 0, [1,0,0],False],
                       volume=(6,6,6,6))

print(np.real(ct[:,0] / 6**3))

[0.0921947  0.03158469 0.00191528 0.00722483 0.00191528 0.03158469]
[0.08815108 0.02460635 0.00158327 0.00467681 0.00158327 0.02460635]


In [9]:
ct = corr.generate_npt(spinTasteMassNaikMomDag1=["G5", "GZ", 0.1, 0, [0,0,0],True],
                       spinTasteMassNaikMomDag2=["G5", "GZ", 0.1, 0, [0,0,0],False],
                       volume=(4,4,4,4))

print(np.real(ct[:,0] / 4**3))

[ 1.80819076e-02  4.22012631e-02 -3.65085300e-34  4.22012631e-02]
